### ISSUE TITLE
Printing Images - Height

### ISSUE THREAD

**Issue by Gi4nfratti** [lukevp/ESC-POS-.NET#111]
Hello, first of all, the library is incredible!! I made a [question](https://stackoverflow.com/questions/67288683/print-image-esc-pos) on Stackoverflow (for more details), about the height of the image when I print. I'm using Xamarin Android, I created a bitmap with SkiaSharp and save it as PNG. It's perfectly saved on my device. But when I'll print it, the necessary height to print the whole bitmap is not matching. I tried with [this](https://logosmarcas.net/wp-content/uploads/2020/04/Nike-Logo.png) image, it's a logo with a width more larger than the height, 3840x2160, and it worked perfectly. And my bitmap have the height more larger than the width (it's a list), 700 of width and 1280 of height. Both images are PNG and 72 of DPI. I'm reducing the width as follows:

` buffer = ByteSplicer.Combine( e.PrintImage(logo, true, true, 372, 0) );`

If I don't reduce the width, it prints a lot of random characters.
The width is perfect, but I have the height similar to the first image, it seems a "logo size".

Can you show an example of how can we print images/bitmaps that have a big height like a list without cutting/limiting it?

Tests:
I Printed this PNG file:
![Nike-Logo](https://user-images.githubusercontent.com/32543785/116574539-329b9900-a8e4-11eb-9e05-47a6b18c4fa2.png)

And this is the result:
![nikeResult](https://user-images.githubusercontent.com/32543785/116575380-f6b50380-a8e4-11eb-80ee-88c9d0a0367b.jpeg)

But when I print this:
![verticalLogo](https://user-images.githubusercontent.com/32543785/116575440-059bb600-a8e5-11eb-9b65-96579eb73ef8.png)

That's the result:
![verticalResult](https://user-images.githubusercontent.com/32543785/116575511-164c2c00-a8e5-11eb-9090-88fe4b0b509b.jpeg)

In this test, it still shows this thing next to the sticker, but with another image that I tested, it printed the height of the sticker (same cutted as the test above) and just it.

**Comment by lukevp** [comment]
Hi, sorry for the delay getting back to you.  What happens if you set the width on the image and print it?  Are there other too-tall images that print correctly?  The reason I ask is that the bar prints the whole way down, so that makes me think the problem might be with the PNG you are using and not with the lib resizing the image.

**Comment by Gi4nfratti** [comment]
Hello, no problem. This was resolved by dividing the bitmap in parts of 256px of height and then printing.

**Comment by jjxtra** [comment]
Had to do something similar, sharing for future generations...

```cs
    private static IEnumerable<Image<Rgba32>> ExtractChunks(Image<Rgba32> sourceImage)
    {
        const int chunkSize = 256;
        for (var y = 0; y < sourceImage.Height; y += chunkSize)
        {
            Rectangle sourceArea = new(0, y, sourceImage.Width, Math.Min(sourceImage.Height - y, chunkSize));
            if (sourceArea.Height < 1)
            {
                yield break;
            }
            Image<Rgba32> targetImage = new(sourceArea.Width, sourceArea.Height);
            int height = sourceArea.Height;
            sourceImage.ProcessPixelRows(targetImage, (sourceAccessor, targetAccessor) =>
            {
                for (int i = 0; i < height; i++)
                {
                    Span<Rgba32> sourceRow = sourceAccessor.GetRowSpan(sourceArea.Y + i);
                    Span<Rgba32> targetRow = targetAccessor.GetRowSpan(i);

                    sourceRow.Slice(sourceArea.X, sourceArea.Width).CopyTo(targetRow);
                }
            });
            yield return targetImage;
        }
    }
```

**Comment by nivle** [comment]
I ended up doing solving this like this.....(to solve some buffer issue), which is kind of the same as setting legacymode to true I guess)... though in this way you have some more control over the size...

```

IList<byte[]> data = new List<byte[]>
            {
                epson.CenterAlign()
            };

Image image = Image.FromStream("///");//add here your image

int size = 256;

for (int i = 0; i < Math.Round((double)image.Height / size, 0, MidpointRounding.ToPositiveInfinity); i++)
{
    int width = image.Width;
    int height = size * (i + 1) <= image.Height ? size : image.Height - (size * i);

    Bitmap newImage = new Bitmap(width, height);

    using (Graphics graphics = Graphics.FromImage(newImage))
    {
        graphics.DrawImage(image, new Rectangle(0, 0, width, height), new Rectangle(0, i * size, width, height), GraphicsUnit.Pixel);
    }

    using (MemoryStream memoryStream = new MemoryStream())
    {
        newImage.Save(memoryStream, ImageFormat.Tiff);
        data.Add(epson.PrintImage(memoryStream.ToArray(), true));
    }
}

data.Add(epson.FullCutAfterFeed(0));

return ByteSplicer.Combine(data.ToArray());


```
