### ISSUE TITLE
Github Project add Topics

### ISSUE THREAD

**Issue by tinohager** [lukevp/ESC-POS-.NET#114]
Hi, is it possible to add some `Topics` to your project? So that it can be found better?

![image](https://user-images.githubusercontent.com/8215186/121149582-13791b00-c843-11eb-950d-2c3b9b211233.png)
For example here an other project
https://github.com/igorocampos/ESCPOS

**Comment by lukevp** [comment]
Thanks @tinohager for the recommendation, didn't know about this! Added some topics. Any other improvements you could suggest? feel free to open another issue!
