### ISSUE TITLE
SixLabors.ImageSharp conflict with Xamarin 5.0 and Android

### ISSUE THREAD

**Issue by antoniodlp** [lukevp/ESC-POS-.NET#139]
Whenever I call PrintImage() on Xamarin 5.0 Android I am getting this error:

`Method not found: System.Span1<!0> SixLabors.ImageSharp.Image1.GetPixelRowSpan(int)`

Any ideas?

**Comment by lukevp** [comment]
Hey @antoniodlp, hope you resolved this issue, but if not, take a look here.  This looks like a problem in the xamarin implementation, but the Sixlabors issue tracker mentions the fix. https://github.com/SixLabors/ImageSharp/issues/1542
