### ISSUE TITLE
Stranger thing

### ISSUE THREAD

**Issue by hackdan** [lukevp/ESC-POS-.NET#140]
The following error happens to me: it prints fine and after a while I sometimes printed strange characters ... watch the picture

https://ibb.co/SK1FrS3

**Comment by igorocampos** [comment]
![image](https://user-images.githubusercontent.com/10572656/141496090-ca46cbed-bc66-49f6-8c1c-a04a0ce44742.png)

**Comment by igorocampos** [comment]
Here you go, your image:


![image](https://user-images.githubusercontent.com/10572656/141496090-ca46cbed-bc66-49f6-8c1c-a04a0ce44742.png)

**Comment by igorocampos** [comment]
Sounds like is something messing up with the image bytes buffer. See how it kind of started to print the same picture twice, without finishing it up first?

Do you have concurrent threads that send bytes to the same printer?

**Comment by lukevp** [comment]
Kind of looks like the printer didn't receive the bytes correctly or overflowed the buffer.  I saw this type of printing happen a lot when I was printing the image.  Does the large images test pass successfully on this printer?  What about if you add 2x or 3x the # of images?

**Comment by hackdan** [comment]
Ok, I'll try again with a simpler image and share the results with you.

**Comment by hackdan** [comment]
Thank you by the support. Now it works like a charm.
