### ISSUE TITLE
virtual COM port emulator

### ISSUE THREAD

**Issue by hosamyousof** [lukevp/ESC-POS-.NET#202]
Can you please guide us with tool name to map the printer to a specific port.

Our printers is now EPSON and we couldn't use print via USB.

As it appears the printer port is USB001 in Printer Properties. How to map it to COM2 for example.

![image](https://user-images.githubusercontent.com/16549201/200837106-ffef67ee-d25e-413b-957c-04bb5701a7d4.png)

Thank you.

**Comment by lukevp** [comment]
@hosamyousof You must use the Virtual COM Port Utility from Epson to map the printer.  It is a separate program on Windows that you must install and configure, and it lets you choose a USB device and a serial port to associate it.  The README has more directions. Closing for now, but if you find an issue with this implementation, let me know and I can reopen if there's a bug.
