### ISSUE TITLE
2 images - side by side

### ISSUE THREAD

**Issue by markrye** [lukevp/ESC-POS-.NET#207]
I can print qr codes and images. 
I need to print 2 images side by side.
How / is this possible?

**Comment by markrye** [comment]
Found solution.
Using skiasharp to manipulate defined background layer, then adding the forground images.
Printing it as one image.

**Comment by lukevp** [comment]
Glad you were able to solve this!  There is also page mode, which allows you to print anywhere on the paper, but the library doesn't currently support that mode.
