### ISSUE TITLE
Label Printing Support?

### ISSUE THREAD

**Issue by monsterkane05** [lukevp/ESC-POS-.NET#236]
Hi,

I was wondering if there is any planned support for label printers which use ESC/POS such as the Epson TM-L90. mainly the feed to label mark, and feed to cutter commands.  this library can be used to print to them but labels end up being out of line due to them not being able to start at the top of the label.

these are some of the commands from epsons website 

FS ( L | Select label and black mark control function(s) | Printing Paper
FS ( L <fn=33> | Paper layout setting | Printing Paper
FS ( L <fn=34> | Paper layout information transmission | Printing Paper
FS ( L <fn=48> | Transmit the positioning information | Printing Paper
FS ( L <fn=65> | Feed paper to the label peeling position | Printing Paper
FS ( L <fn=66> | Feed paper to the cutting position | Printing Paper
FS ( L <fn=67> | Feed paper to the print starting position | Printing Paper
FS ( L <fn=80> | Paper layout error special margin setting | Printing Paper

**Comment by lukevp** [comment]
Hey @monsterkane05 !

This repo is open to PRs, and it's super easy to add new command sets.  You should be able to follow the same conventions as the other commands to add these in.  Are you interested in contributing that? Would be happy to merge and re-release the nuget package with this, as it seems like a straightforward change.

I've been focusing on supporting the most commonly-used commands in favor of supporting every command under the sun, so if there are only a couple really useful ones in this command set then I'm good with just doing those.

**Comment by monsterkane05** [comment]
Yeah im happy to give it a try, reas
