### ISSUE TITLE
Windows and Linux support

### ISSUE THREAD

**Issue by detectivejd** [lukevp/ESC-POS-.NET#244]
Hi, how are you? I wait that you are fine, I have a question: ESC-POS-.NET has support to windows 10?

The description talks that the library has linux support but in the windows part mentions only windows 7. I need a library to print thermical printers in windows greater than windows 7 and any linux distributions.

I´m using .net 7 (.net core) to develop with c#

I wait an answer and greetings.

**Comment by igorocampos** [comment]
Yes, it does work on Windows 10, I believe you missed the `+` sign after Windows 7, indicating that it works for windows 7 and later versions.
![image](https://github.com/lukevp/ESC-POS-.NET/assets/10572656/9016c83c-d0d6-435e-9f1a-279eae1a47d0)
