### ISSUE TITLE
Can't print Image

### ISSUE THREAD

**Issue by asafgo** [lukevp/ESC-POS-.NET#25]
Hi,
When printing image the results is like in the picture.
![POSImage](https://user-images.githubusercontent.com/12719112/64314254-0288df00-cfb7-11e9-842e-44882fd33c1e.jpg)

**Comment by lukevp** [comment]
@asafgo thanks for trying the library! Can you specify what printer you're using, how it's connected, and what driver? This looks like an issue w/ a driver not passing raw commands through.

**Comment by asafgo** [comment]
Hi,
My printer is [http://www.zywell.net/product/ZY606-Thermal-Receipt-Printer.html](url)

**Comment by lukevp** [comment]
Can you try using branch feature/8-dithering-images and try a legacy print? There are 2 different print commands and non-epson printers do not always implement the latest command set for ESC/POS.

**Comment by asafgo** [comment]
I am sorry but I didn't understood what should I do?
What are the 2 different print commands please? so I will ask the manufacturer of the printer.

**Comment by lukevp** [comment]
Check out the branch feature/8-dithering-image instead of master. Then run EscPos.ConsoleTest and choose "legacy images" as the test. See if that works!

**Comment by asafgo** [comment]
Yes! Legacy Print works perfect.
![POSImage2](https://user-images.githubusercontent.com/12719112/64344349-f1f85900-cff6-11e9-97a8-765d9ee4a738.jpg)

**Comment by lukevp** [comment]
Hey @asafgo  thanks for the follow up, glad the legacy print works! I will add an enhancement request to make different emitters, and for non-EPSON emitters it will use the legacy print technique by default.

**Comment by MitkoMitrov** [comment]
Hey @lukevp I cannot find the branch that You mentioned before. Could You help me, I got the same error as @asafgo. Thanks in advance.
