### ISSUE TITLE
is there Indian rupee sign ⟨₹⟩ in codepage?

### ISSUE THREAD

**Issue by Shubhsq2612** [lukevp/ESC-POS-.NET#252]
Hi, i am using it inside xamarin, but it is not printing the indian rupee. Can anyone telll me the code page for this.
thank you.

**Comment by lukevp** [comment]
Hi @Shubhsq2612 , you will have to look up the codepages in the Epson docs as well as your printer's docs (if using a non-Epson printer).  Not all printers implement all code pages.  Please see #256 for reference on how we can expand the code page support, but this is a question that's specific to your implementation, not one we can generically answer for you.
