### ISSUE TITLE
SerialPrinter bug?

### ISSUE THREAD

**Issue by koo9** [lukevp/ESC-POS-.NET#279]
it looks like the write(byte[] data) only put the byte[] into the queue but not sending it to the COM port.

**Comment by igorocampos** [comment]
Hi, I took a look at Serial Printer and it doesn't have any specific implementation of Write method you mentioned, which means it uses the base class one, also used in all other printer classes. 

Dequeue from buffer doesn't happen in the Write method, but rather at `WriteLongRunningTask` which is a background task that does the actual writing to the binary writer (in your case it's the COM port, as you can check in the Serial Printer class constructor)

My suggestion for your debugging is to put a break point [here](https://github.com/lukevp/ESC-POS-.NET/blob/a211dfb22ae5b8fef2339ee0328fb62e981198fa/ESCPOS_NET/Printers/BasePrinter.cs#L106) so you know bytes successfully dequeued from the buffer and are about to get written in the writer, and also [here](https://github.com/lukevp/ESC-POS-.NET/blob/a211dfb22ae5b8fef2339ee0328fb62e981198fa/ESCPOS_NET/Printers/BasePrinter.cs#L96) to know if IsConnected flag isn't `false` for whatever reason.

**Comment by koo9** [comment]
@igorocampos yes, the SerialPrinter class  derive from the BasePrinter, the write(byte[] data) method queue data into the queue, the init() function supposed to start the writeLongRunningTask in another thread.

**Comment by igorocampos** [comment]
And has it, in your case? I'm not saying that there's no bug, but my gut says it's more likely to have a serial port connection/usage issue, rather than a code logic one, since the same code is working elsewhere.

**Comment by koo9** [comment]
turned out that the printer support ESC/POS mode but not direct IP print, it needs to go through a serial port mapping to the printer. so closing this issue.
