### ISSUE TITLE
Thread.Abort raise PlatformNotSupportedException

### ISSUE THREAD

**Issue by oachkatzalschwoaf** [lukevp/ESC-POS-.NET#35]
in the Dispose-method of BasePrinter
 `_readThread?.Abort();` throws `PlatformNotSupportedException` when the target-framework is set to .NET Core  ( e.g. your testproject; ESCPOS_NET.ConsoleTest )

see: [https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort )

**Comment by lukevp** [comment]
hey @kodejack is this fixed by your PR?  @oachkatzalschwoaf  you could check open PR #37 to see if it is fixed, this seems related to what kodejack was addressing.

**Comment by oachkatzalschwoaf** [comment]
> hey @kodejack is this fixed by your PR? @oachkatzalschwoaf you could check open PR #37 to see if it is fixed, this seems related to what kodejack was addressing.

Yes he fixed this issue. => I've done a quick test with my Network printer (just dispose each time after printing then reconnect).

**Comment by kodejack** [comment]
Great! Glad it's sorted.

**Comment by oachkatzalschwoaf** [comment]
Fixed in Master
