### ISSUE TITLE
add support for QR / Barcode printing

### ISSUE THREAD

**Issue by lukevp** [lukevp/ESC-POS-.NET#4]

**Comment by juliogamasso** [comment]
Good night, @lukevp. I implemented the generation QrCode in the library. You could evaluate and help me to fix something if you find it necessary? My Printers are working, but I would appreciate your evaluation if i don't bother. Can I send via PR?

**Comment by lukevp** [comment]
Sounds good, thanks! There is some barcode support already but I would like
to add some checking to the input data, and adding QR codes will be great.

**Comment by lukevp** [comment]
QR and Barcode printing are supported in 1.0.0 release.
