### ISSUE TITLE
Does not print accents

### ISSUE THREAD

**Issue by ChipiCoding** [lukevp/ESC-POS-.NET#41]
I have Encoding "IBM865"

Á Í Ó Ú upper case => does not print 

á é í ó ú =>  print ok

Encoding = Encoding.GetEncoding("IBM865")

byte[] IPrinterTemplate.Receipt(ICommandEmitter e) =>
            ByteSplicer.Combine(
            e.CenterAlign(),
            e.SetBarWidth(BarWidth.Default),
            Encoding.GetBytes(PrintHeader(PrintSaleModel.Header.Company))
}

**Comment by lukevp** [comment]
Is this related to the character encoding on the printer itself?  What printer do you have? I believe you need to set it using a separate character page command, we don't have support for that but it should be pretty straightforward to add.

**Comment by lukevp** [comment]
@ChipiCoding  any update on this?
