### ISSUE TITLE
Where do I find definitions such as Ops.PaperCut?

### ISSUE THREAD

**Issue by liudr** [lukevp/ESC-POS-.NET#43]
Hi I was looking for some sort of .h file for these definitions but couldn't find any? I program in C/C++, not C# but found it useful to compare my code with your for correctness. You have a very good list of commands by functions, better than epson official docs in my opinion. Thanks.

**Comment by lukevp** [comment]
@liudr Hi, thanks for the star and appreciate the kind words!

I see where the confusion was and the previous structure of these properties was poor.  I've refactored the library and included these types in a separate directory.

Please let me know if that helps and is easier to read.
BaseCommandValues is the directory you're looking for that contains all the static single byte exports, and BaseCommandEmitter is what builds the combined byte arrays to represent a command.

https://github.com/lukevp/ESC-POS-.NET/tree/master/ESCPOS_NET/Emitters
