### ISSUE TITLE
add support for fluent api on byte builder

### ISSUE THREAD

**Issue by lukevp** [lukevp/ESC-POS-.NET#5]

**Comment by montyclt** [comment]
See this class https://github.com/vadavo/NEscPos/blob/master/Vadavo.NEscPos/Helpers/PrintableBuilder.cs

**Comment by lukevp** [comment]
@montyclt Think this is satisfied on release/1.0 branch with ByteArrayBuilder Append methods.  Can you confirm?

**Comment by lukevp** [comment]
@montyclt Check out PR #30 and comment there please!

**Comment by montyclt** [comment]
> @montyclt Check out PR #30 and comment there please!

https://github.com/lukevp/ESC-POS-.NET/commit/7221d72458bd3039384cca159ba935be651c0d8e#commitcomment-35359946

**Comment by lukevp** [comment]
Included in 1.0.0 release.
