### ISSUE TITLE
EPSON Printer

### ISSUE THREAD

**Issue by sebastianbouckaert** [lukevp/ESC-POS-.NET#57]
I have a question on how to connect a usb device.
I have an official epson printer, but I have no idea how to connect it to the code...

**Comment by lukevp** [comment]
@sebastianbouckaert which platform are you on? There is a usage guide in the readme, if anything is unclear please let me know or send a PR for the readme that clarifies! Thanks.
https://github.com/lukevp/ESC-POS-.NET#usb-usage-guide

**Comment by lukevp** [comment]
Closed due to inactivity.
