### ISSUE TITLE
How to print logo from a Xamarin Forms Application

### ISSUE THREAD

**Issue by N4511** [lukevp/ESC-POS-.NET#66]
Hi, I am trying to print logo using this nuget package. Could not figure out how to print the logo yet.  I have tried getting  image byte code using the webclient.downloadData("ImageURL"). But it only prints gibberish instead of the logo itself. Could you be kind enough to share how to print a logo from Xamarin forms application. Thanks.

**Comment by lukevp** [comment]
Hey @N4511 thanks for trying the library out.  Do you have an Epson printer?  Can you try printing from outside of the Xamarin app (directly on Windows) using the test app to see if it works correctly?

**Comment by N4511** [comment]
Thanks for coming back to me so quickly. My printer is not a Epson printer. I should try to print using the test print. Thanks. But if you could figure out how to print from a xamarin forms would be highly appreciated.

**Comment by N4511** [comment]
Just used the test app. And the result is still the same. I guess it's an issue on my printer side. Thanks.

**Comment by lukevp** [comment]
@N4511 What printer do you have? What OS and Driver?

**Comment by N4511** [comment]
The model of my receipt printer is BTP-R180ii and the make is SNBC. It uses its generic windows driver that has been provided by the maker. Thanks.

**Comment by lukevp** [comment]
Could you put up an example Xamarin forms app? Or make a PR to this repo with another example? I can give it a try with my printer to see if I can find the issue.

**Comment by lukevp** [comment]
closing due to staleness.
