### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by varunbhoopalam3** [lukevp/ESC-POS-.NET#73]
Please let me know if your nuget supports adding QRCode to the receipt? Thanks.

**Comment by varunbhoopalam3** [comment]
Got it. The below line worked.
printer.Write(ByteSplicer.Combine(e.Print2DCode(TwoDimensionCodeType.QRCODE_MICRO, document.DocNumber)));

Is there a way to increase the size of the QR Code?

**Comment by lukevp** [comment]
hey @varunbhoopalam3  glad you answered your own question, and thanks to @igorocampos for the QR code implementation!

**Comment by igorocampos** [comment]
Any time

**Comment by igorocampos** [comment]
@lukevp maybe we could provide some default parameters to that Print2DCode, or an alias like PrintQRCode that would call Print2DCode with some default parameters. I think people would embrace it better
