### ISSUE TITLE
Add support for virtual port

### ISSUE THREAD

**Issue by tematim** [lukevp/ESC-POS-.NET#76]
Hello,

I have a printer TSP100 link to a computer by USB and Windows create a virtual port.

As I don't know if it's possible to have an internal redirection, it will be nice is your package is able to communicate with this kind of port.

I try to force the value like comPort = "USB001"; but I have an exeception because it's awaiting a COMX value.

Regards

**Comment by lukevp** [comment]
This is a limitation of the System.Windows.Ports .NET serial port library on Windows, unfortunately.  You will have to install a driver that maps a virtual port to a named COM port.
