### ISSUE TITLE
Failure to communicate with the Pos printer used via USB

### ISSUE THREAD

**Issue by ahoirg** [lukevp/ESC-POS-.NET#90]
Failure to communicate with the Pos printer used via USB. May be related to this issue #76 .

I could not communicate with the printer using this method. Printer also tested with another test application. It worked.

> // USB, Bluetooth, or Serial
var printer = new SerialPrinter(portName: "COM5", baudRate: 115200);

![image](https://user-images.githubusercontent.com/17729246/99267656-491dce80-2835-11eb-80a4-0fd57c898a14.png)

**Comment by lukevp** [comment]
Hey @ahoirg this library works with USB printers fine, but you must use a virtual COM port emulator since it doesn't speak USB directly.  More info [in the readme](https://github.com/lukevp/ESC-POS-.NET#usb-usage-guide. Which test application did you use?
