### ISSUE TITLE
ESC/POS commands 

### ISSUE THREAD

**Issue by dicksonkimeu** [lukevp/ESC-POS-.NET#97]
How can i pass some ESC/POS commands to the printer ?

I.e

string ESC = "0x1B"; //ESC byte in hex notation
string NewLine = "0x0A"; //LF byte in hex notation

    string cmds = ESC + "@"; //Initializes the printer (ESC @)
    cmds += ESC + "!" + "0x38"; //Emphasized + Double-height + Double-width mode selected (ESC ! (8 + 16 + 32)) 56 dec => 38 hex
    cmds += "BEST DEAL STORES"; //text to print
    cmds += NewLine + NewLine;
    cmds += ESC + "!" + "0x00"; //Character font A selected (ESC ! 0)
    cmds += "COOKIES                   5.00"; 
    cmds += NewLine;
    cmds += "MILK 65 Fl oz             3.78";

**Comment by lukevp** [comment]
Hi @dicksonkimeu ,
Please read the README for examples on library usage. We do not directly use ESC commands like this, that is one of the purposes of the library.
